{% set name = "fast_vindex" %}
{% set version = "0.0.2" %}
{% set python_min = "3.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: f904896aad083e07d6a5141e1c43939030edf2b440b9d01725c74065eb5626b8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - pip
    - hatchling
  run:
    - python >={{ python_min }}
    - dask >=2025.1.0
    - pandas >=2.2
    - numpy >=1.26
    - xarray >=2024.10.0
    - matplotlib-base >=3.8

test:
  imports:
    - fast_vindex
  requires:
    - python {{ python_min }}
    - pip
  commands:
    - pip check

about:
  home: https://gitlab.ifremer.fr/odatis-public/fast_vindex
  license: LGPL-3.0-or-later
  license_file: LICENSE
  summary: 'A faster version of Dask’s vindex for advanced indexing with arrays.'

extra:
  recipe-maintainers:
    - GwenaelCaer
